### ISSUE TITLE
When are container scheduled for refresh?

### ISSUE THREAD

**Issue by Thorndike** [puppetlabs/puppetlabs-docker#138] opened 2018-02-01 13:24 UTC
I am using puppetlabs-docker (v1.0.4) with puppet 4.10.9 on RHEL 7.4. My problem is that I can not figure out when containers are scheduled for refresh. If I change the docker::run configuration for some of many containers running on a host sometimes all running containers are scheduled for refresh (meaning restartet). I expect that restart for containers with changes in configuration but all other should stay untouched.

So far I see no reason in restarting all containers on a host. What am I missing and how can I prevent all untouched containers from restarting?

**Comment by Thorndike** [comment] 2018-02-02 09:12
It seems the unexpected restarts of containers have something to do with this message:

`Notice: /Stage[main]/Logspout/Docker::Run[logspout]/File[/etc/systemd/system/docker-logspout.service]/seltype: seltype changed 'systemd_unit_file_t' to 'container_unit_file_t'
Info: /Stage[main]/Logspout/Docker::Run[logspout]/File[/etc/systemd/system/docker-logspout.service]: Scheduling refresh of Service[docker-logspout]
Info: /Stage[main]/Logspout/Docker::Run[logspout]/File[/etc/systemd/system/docker-logspout.service]: Scheduling refresh of Exec[docker-logspout-systemd-reload]
`

But I have no idea what to change in the configuration to prevent that from happening.

**Comment by Thorndike** [comment] 2018-02-09 09:40
New Info: I monitored the selinux labels of the service files and it seems that docker::run ist changing them both ways. I really have no clue how to tell the plugin to keep one and the same label for those files and do need some support here:

`Feb  9 10:22:27 rhscpm026 puppet-agent[5352]: (/Stage[main]/Main/Node[rhscpm026.ecofis.de]/Docker::Run[ctosso-mock]/File[/etc/systemd/system/docker-ctosso-mock.service]/seltype) seltype changed 'systemd_unit_file_t' to 'container_unit_file_t'


Feb  9 10:23:14 rhscpm026 puppet-agent[10102]: (/Stage[main]/Main/Node[rhscpm026.ecofis.de]/Docker::Run[ctosso-mock]/File[/etc/systemd/system/docker-ctosso-mock.service]/seltype) seltype changed 'container_unit_file_t' to 'systemd_unit_file_t'
`

**Comment by davejrt** [comment] 2018-02-15 23:19
Just to clarify the issue here, as I'm not 100% sure based on your initial question. That when you change the docker::run config for one container, all of them get restarted?

>  that docker::run ist changing them both ways

Is it or isn't?

Can you send me an example of your manifest before and after that's causing the errors?

**Comment by Thorndike** [comment] 2018-02-19 07:01
Exactly that is my observation, I change on of the docker::run configurations on my master server an puppet restarts all defined containers on that node because puppet changed the selinux label of the systemd files in the background (I have puppet running as a service).

To my knowledge the manifest (pp files and classes) does not change and I was not able to determine where the definitions of the selinux labels are made.

**Comment by Thorndike** [comment] 2018-02-20 06:33
First, the current Versions of plugins I have installed:

`etc/puppetlabs/code/modules
├─┬ maestrodev-ant (v1.0.5)
│ ├── maestrodev-wget (v1.7.3)
│ └── puppetlabs-stdlib (v4.17.1)
├─┬ puppetlabs-apache (v2.3.0)
│ └── puppetlabs-concat (v2.2.1)
├── verzeichnis (???)
├── camptocamp-augeas (v1.6.0)
├── thias-sysctl (v1.0.6)
├── puppet-selinux (v1.5.2)
├─┬ puppetlabs-rsync (v1.0.0)
│ └── puppetlabs-xinetd (v2.0.0)
├── bodgit-rngd (v2.0.0)
├── saz-dnsmasq (v1.3.1)
├─┬ puppetlabs-docker (v1.0.4)
│ ├── puppetlabs-apt (v4.5.0)
│ └── stahnma-epel (v1.2.2)
├─┬ jhoblitt-port389 (v0.1.0)
│ ├─┬ jhoblitt-nsstools (v2.0.0)
│ │ └── camptocamp-openssl (v1.10.0)
│ ├── saz-limits (v2.5.0)
│ ├── domcleal-augeasproviders (v1.2.1)
│ └─┬ camptocamp-openldap (v1.16.1)
│   ├── herculesteam-augeasproviders_core (v2.1.3)
│   └── herculesteam-augeasproviders_shellvar (v2.2.1)
├── puppetlabs-git (v0.5.0)
├── biemond-jdk7 (v1.0.0)
├── puppetlabs-ntp (v6.2.0)
├── maestrodev-maven (v1.4.0)
├── mycert (???)
├─┬ puppetlabs-mysql (v5.2.0)
│ ├── puppetlabs-translate (v1.1.0)
│ └── puppet-staging (v3.1.0)
└── mysmtp (???)
`
Second, the node manifest:

`node 'rhscpm026.ecofis.de' {
  include cpuser
  include docker_base_setup
  include ensure_sshdir
  include authorize_ecofis
  include authorize_ecofis_management
  include authorize_puppet_master

  file { ["/opt/ssl"]:
    ensure => "directory",
    owner  => "root",
    group  => "root",
    mode   => '777',
  }

  file { ["/opt/ssl/ECOFISServerCA2015.crt"]:
    require         => File["/opt/ssl"],
    source => "puppet:///modules/mycert/ECOFISServerCA2015.crt",
  }

  file { ["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt"]:
    require         => File["/opt/ssl"],
    source => "puppet:///modules/mycert/cto-mock.cpint.cp.creditreform.de.crt",
  }

  file { ["/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"]:
    require         => File["/opt/ssl"],
    source => "puppet:///modules/mycert/cto-mock.cpint.cp.creditreform.de.key",
  }

  class { selinux:
    mode => 'permissive',
    type => 'targeted',
  }

  file { "/root/clean-docker.sh":
    ensure  => "present",
    content => '#!/bin/bash
/usr/bin/echo $(/usr/bin/date +%Y-%m-%d:%H:%M:%S) >> /var/log/rm.log && /usr/bin/docker ps -q -a | /usr/bin/xargs /usr/bin/docker rm -v >> /var/log/rm.log
/usr/bin/echo $(/usr/bin/date +%Y-%m-%d:%H:%M:%S) >> /var/log/rmi.log && /usr/bin/docker rmi $(/usr/bin/docker images | /usr/bin/grep "^<none>" | /usr/bin/awk "{print $3}") >> /var/log/rmi.log
/usr/bin/docker rmi $(docker images -a -q)  >> /var/log/rmi.log
',
  mode => '755',
  }

cron { 'docker_clean':
  command => '/root/clean-docker.sh',
  user    => 'root',
  hour    => ['2'],
  minute  => '0',
  require => File["/root/clean-docker.sh"],
}

  $ctossoMockInst1="0.4.0-201701111008"

  docker::run { "ctosso-mock" :
    image   => "docker-registry.cp.creditreform.de/mock/cto_sso_mock:$ctossoMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8443:8443", "8080:8080", "9999:9999"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,ctosso-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $ctoMockInst1="2.3.0-201801301306"

  docker::run { "ctoMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/cto_auskunft_mock:$ctoMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8444:8443", "8081:8080", "9998:9999"],
    memory_limit    => '1000m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,cto-a-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $ctovMockInst1="2.4.0-SNAPSHOT-201802071409"

  docker::run { "ctovMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/cto-v-mock:$ctovMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8445:8443", "8082:8080", "9997:9999"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,cto-v-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $ctlMockInst1="2.3.0-201801031529"

  docker::run { "ctlMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/ctl_auskunft_mock:$ctlMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8446:8443", "8083:8080", "9996:9999"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,ctl-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $ctoPumacMockInst1="0.2.0-SNAPSHOT-201708031333"

  docker::run { "ctoPumacMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/cto_pumac_mock:$ctoPumacMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8447:8443", "8084:8080", "9995:9999"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,pumac-mock",
             "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
           ],
  }

  $ctoiMockInst1="2.2.1-SNAPSHOT-201802021135"

  docker::run { "ctoiMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/cto-i-mock:$ctoiMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8448:8443", "8085:8080", "9993:9999"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,cto-i-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $supplierInquiryMockInst1="0.4.0-201706301021"

  docker::run { "supplier_inquiry_mock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/supplier-inquiry-mock:$supplierInquiryMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8450:8443", "8087:8080"],
    memory_limit    => '400m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "LOGSTASH_TAGS=cpint,supplier-mock",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            ],
  }

  $fiwiMockInst1="1.4.0-201801261217"

  docker::run { "fiwiMock_inst1" :
    image   => "docker-registry.cp.creditreform.de/mock/fiwi-mock:$fiwiMockInst1",
    dns     => ['10.2.49.10', '10.2.49.20', '10.14.49.20'],
    pull_on_start => true,
    restart_service => true,
    volumes         => ['/opt/ssl:/opt/ssl', '/etc/localtime:/etc/localtime:ro'],
    ports           => ["8451:8443", "8088:8080"],
    memory_limit    => '500m',
    require         => File["/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt", "/opt/ssl/cto-mock.cpint.cp.creditreform.de.key"],
    env => [
            "ECO_SSL_HOST_CRT_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.crt",
            "ECO_SSL_HOST_KEY_FILE=/opt/ssl/cto-mock.cpint.cp.creditreform.de.key",
            "JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n -Xmx256m -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Berlin",
            "LOGSTASH_TAGS=devAsk,fiwi-mock",
           ],
  }

}
`

Finally the included docker setup:
`class docker_base_setup {

  class { 'docker':
    use_upstream_package_source => false,
    service_overrides_template  => false,
    docker_ce_package_name      => 'docker',
    selinux_enabled             => 'true',
    repo_opt =>	'',
    extra_parameters => "-H 0.0.0.0:2375 --insecure-registry dev.registry.ecofis.de:30113 --insecure-registry docker-registry.cp.creditreform.de --insecure-registry registry.docker.ecofis.de --insecure-registry extern-registry.cp.creditreform.de:443 --dns 10.2.49.10 --dns 10.2.49.20 --dns 10.14.49.10",
  }

  docker::registry { 'docker-registry.cp.creditreform.de':
    require => Service["docker"],
    username => '****',
    password => '****',
    version  => '<docker_version>',
  }

  docker::registry { 'extern-registry.cp.creditreform.de:443':
    require => Service["docker"],
    username => '****',
    password => '****',
    version  => '<docker_version>',
  }

}

`

**Comment by davejrt** [comment] 2018-02-21 03:46
You can see this [log](https://gist.github.com/davejrt/1d6d66b308034c27aac7d452c075f939). I have the following manifest applied, before the second run I changed the port number for the `dave` container and the nginx1 container remainds untouched:
```
node default {

class { selinux:
  mode => 'permissive',
  type => 'targeted',
}

  class {'docker':
    selinux_enabled => 'true',
  }

  docker::run {'nginx1':
    ports => ['80'],
    image => 'nginx:stable-alpine',
    pull_on_start => true,
  }

  docker::run {'dave':
    ports => ['8000'],
    image => 'nginx:stable-alpine',
    pull_on_start => true,
  }
}
```

**Comment by Thorndike** [comment] 2018-02-21 06:30
The change of the selinux label occurs when the puppet agent is running as a service in the background. If you do a "puppet agent -t" twice, only the touched configuration will be restarted.
Please check the the selinux labels of the generated services with "ls -Z /etc/systemd/system/docker*". If it says "systemd_unit_file_t" the container will be restarted, if it says "container_unit_file_t" the container will not be touched. The problem is that the puppet service, for no reason obvious to me, changes the label to "systemd_unit_file_t" while running in the background.

Your service files initially had the label "unlabeled_t" and it was changed to the expected "container_unit_file_t" . The open question is: who ist setting  "systemd_unit_file_t"?

**Comment by davejrt** [comment] 2018-02-22 06:26
I can't replicate that behaviour in my test environment. If you have puppet running the background, and you think that's what is changing it, then there should be a log of that event. 

With the same manifest, applied, rebooted to activate selinux then puppet applied again I get the following output
```
[root@bpw5k5w8tsj6ayq ~]# puppet apply /tmp/default.pp
Notice: /File[/etc/puppetlabs/code/environments/production]/seltype: seltype changed 'unlabeled_t' to 'puppet_etc_t'
Notice: Compiled catalog for bpw5k5w8tsj6ayq.delivery.puppetlabs.net in environment production in 0.57 seconds
Notice: /Stage[main]/Selinux::Config/File[/opt/puppetlabs/puppet/cache/puppet-selinux]/seltype: seltype changed 'unlabeled_t' to 'usr_t'
Notice: /Stage[main]/Selinux::Config/File[/opt/puppetlabs/puppet/cache/puppet-selinux/bin]/seltype: seltype changed 'unlabeled_t' to 'bin_t'
Notice: /Stage[main]/Selinux::Config/File[/opt/puppetlabs/puppet/cache/puppet-selinux/bin/selinux_build_module_simple.sh]/seltype: seltype changed 'unlabeled_t' to 'bin_t'
Notice: /Stage[main]/Selinux::Config/File[/opt/puppetlabs/puppet/cache/puppet-selinux/modules]/seltype: seltype changed 'unlabeled_t' to 'usr_t'
Notice: /Stage[main]/Docker::Service/File[/etc/sysconfig/docker-storage-setup]/seltype: seltype changed 'unlabeled_t' to 'etc_t'
Notice: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d]/seltype: seltype changed 'unlabeled_t' to 'systemd_unit_file_t'
Notice: /Stage[main]/Docker::Service/File[/etc/systemd/system/docker.service.d/service-overrides.conf]/seltype: seltype changed 'unlabeled_t' to 'container_unit_file_t'
Notice: /Stage[main]/Docker::Service/Exec[docker-systemd-reload-before-service]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Docker::Service/File[/etc/sysconfig/docker-storage]/seltype: seltype changed 'unlabeled_t' to 'etc_t'
Notice: /Stage[main]/Docker::Service/File[/etc/sysconfig/docker]/seltype: seltype changed 'unlabeled_t' to 'etc_t'
Notice: /Stage[main]/Docker::Service/Service[docker]: Triggered 'refresh' from 3 events
Notice: /Stage[main]/Main/Node[default]/Docker::Run[nginx1]/File[/etc/systemd/system/docker-nginx1.service]/seltype: seltype changed 'unlabeled_t' to 'container_unit_file_t'
Notice: /Stage[main]/Main/Node[default]/Docker::Run[nginx1]/Exec[docker-nginx1-systemd-reload]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Main/Node[default]/Docker::Run[nginx1]/Service[docker-nginx1]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Main/Node[default]/Docker::Run[dave]/File[/etc/systemd/system/docker-dave.service]/seltype: seltype changed 'unlabeled_t' to 'container_unit_file_t'
Notice: /Stage[main]/Main/Node[default]/Docker::Run[dave]/Exec[docker-dave-systemd-reload]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Main/Node[default]/Docker::Run[dave]/Service[docker-dave]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 6.87 seconds
[root@bpw5k5w8tsj6ayq ~]# puppet apply /tmp/default.pp
Notice: Compiled catalog for bpw5k5w8tsj6ayq.delivery.puppetlabs.net in environment production in 0.43 seconds
Notice: Applied catalog in 0.22 seconds
[root@bpw5k5w8tsj6ayq ~]# ls -Z /etc/systemd/system/docker*
-rw-r-----. root docker system_u:object_r:container_unit_file_t:s0 /etc/systemd/system/docker-dave.service
-rw-r-----. root docker system_u:object_r:container_unit_file_t:s0 /etc/systemd/system/docker-nginx1.service

/etc/systemd/system/docker.service.d:
-rw-r--r--. root root system_u:object_r:container_unit_file_t:s0 service-overrides.conf
[root@bpw5k5w8tsj6ayq ~]#
```

I'd suggest you simplify the setup in a sandbox environment and only apply selinux and docker and work from there to see if you can find the issue.

**Comment by rmsds** [comment] 2018-03-20 14:54
I found the same issue (selinux labels flapping causing my containers to be restarted) and I think I found where it comes from.

I think it's due to the behaviour described in this Puppet "bug": [PUP-3187](https://tickets.puppetlabs.com/browse/PUP-3187]).

As I understand it, the puppet agent loads the selinux policies only once, at start time, and will not reload them until restarted. If policies are installed after they won't be taken into account in any runs started by the agent.

So, in a run triggered by the agent Puppet applies the old policies (type context is set to `systemd_unit_file_t`), in a manually triggered run (`puppet agent --test`) it applies the current policies (type context is set to `container_unit_file_t`).

In my case the policies are in the ```container-selinux``` package, and I've managed to reproduce this as follows:
1. uninstall ```container-selinux```
1. start the puppet agent
1. install ```container-selinux```
1. add a file that matches the policy in question with puppet:
```
  file { '/etc/systemd/system/docker-some-service.service':
    ensure  => present,
    content => 'fake-file',
    mode    => '0644',
  }
```
1. run ```puppet agent --test``` -> the file is created with context ```container_unit_file_t```
1. wait for a puppet agent run -> the file context is changed to ```systemd_unit_file_t```
1. run ```puppet agent --test``` -> the file context is changed to ```container_unit_file_t```
1. restart puppet agent -> the file context is never touched again

So, until/unless this behaviour changes in the Puppet agent (making SELINUX policies get reloaded at every run), the workaround I see is to simply restart the puppet agent whenever the policies are changed.

**Comment by Thorndike** [comment] 2018-03-20 14:57
Thank you for that insight! I have for now disabled the agent to get around the problem.

**Comment by rmsds** [comment] 2018-03-20 15:11
@Thorndike simply restarting it after the first installation of docker (and the SELINUX policy files) should be enough actually.

**Comment by davejrt** [comment] 2018-03-20 22:04
I'm going to close this issue as this is not a docker specific issue. Thanks for your advice @rmsds hopefully others find there way here and it's useful for them

**Closed by davejrt** 2018-03-20 22:04 UTC
Labels: question
