### ISSUE TITLE
Facter fails to add docker custom fact when docker isn't installed

### ISSUE THREAD

**Issue by gnufreak** [puppetlabs/puppetlabs-docker#776] opened 2021-09-18 12:31 UTC
While running puppet agent, I'm getting the error below, regardess of the platform on which the client is executing.

`Error: Facter: error while resolving custom fact "docker": undefined method `match?' for nil:NilClass`

in lib/facter/docker.rb:105:

`if docker_version.match?(%r{1[0-9][0-2]?[.]\w+})`

## Expected Behavior

The type of variable should not be assumed and if docker isn't installed, the code shouldn't be checking its version.

## Steps to Reproduce

1. Run puppet agent.

## Environment
 - Version 4.1.1
 - Tested on Linux and FreeBSD

**Comment by kenyon** [comment] 2021-09-19 04:31
Duplicate of #769.

**Comment by adrianiurca** [comment] 2021-10-04 11:32
this was solved and is present in v4.1.2

**Closed by adrianiurca** 2021-10-04 11:32 UTC
