### ISSUE TITLE
APT dependency cycle

### ISSUE THREAD

**Issue by hex2a** [puppetlabs/puppetlabs-docker#42] opened 2017-11-15 12:44 UTC
there is a dependency cycle which seems to be caused by this line, as the `apt::source` docker requires a package, which would be installed after `apt::update`, which requires `apt::source`..
https://github.com/puppetlabs/puppetlabs-docker/blob/148ce5e16407eb3c40415ed2d44090dcfdb16734/manifests/repos.pp#L27

formatted output:
```
(Anchor[apt_key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 present] =>
Apt::Key[Add key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 from Apt::Source docker] =>
Apt::Source[docker] =>
Class[Apt::Update] =>
Exec[apt_update] =>
Class[Apt::Update] =>
Package[debian-keyring] =>
Apt::Source[docker] =>
Apt::Key[Add key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 from Apt::Source docker] =>
Anchor[apt_key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 present])
```

**Comment by hex2a** [comment] 2017-11-15 12:51
this is similar to #369,
I'd submit a PR to remove the `require` relationship and add information in the README instead.

@scotty-c what do you think about this?

**Comment by scotty-c** [comment] 2017-11-15 13:18
@hex2a I have just tested the module and was unable to replicate this issue. 
Are you able to share code examples so we can replicate the issue?

**Comment by hex2a** [comment] 2017-11-15 14:08
```
Apt::Source <| |> -> Class['apt::update'] -> Package <| |>
include ::docker
```

the `$required_packages` param was removed from `apt::source`, stating that those packages should already be installed on a Debian base system.
https://github.com/puppetlabs/puppetlabs-apt/pull/427#issuecomment-75166159

**Comment by davejrt** [comment] 2017-11-16 17:02
We've tested this internally on debian 9 and can't replicate the behaviour. Are you including apt somewhere else in your puppet catalog? If so, there's a param `use_upstream_package_source` which will stop the docker module installing any other packages. 

If this doesn't solve the problem can you provide a full code example, the version of debian, the specific version of the module and the version of puppet you're using.

**Comment by hex2a** [comment] 2017-11-17 15:16
I'm able to reproduce it using Debian 9.1 (Vagrant Box `debian/contrib-stretch64` virtualbox, 9.2.0) and puppet `4.8.2-5` from the Debian repos.

The issue is not in the module per se, but occurs if the (somewhat common) pattern (as above) is used.
```
Apt::Source <| |> -> Class['apt::update'] -> Package <| |>

```

**Comment by scotty-c** [comment] 2017-11-21 20:12
I am closing this issue as there is a workaround for the above workflow setting `use_upstream_package_source => false,` which is how the module should work by design.

**Closed by scotty-c** 2017-11-21 20:12 UTC

**Comment by tpdownes** [comment] 2017-11-28 18:55
@hex2a This is what I do to avoid a cyclic dependency with this module and with repos that I manually manage with the Debian 9 flavor of `puppetlabs-apt`:

```puppet
  # Realize the virtual resources from the list of repos.
  $repos.each |$repo| {
    Apt::Source <| title == $repo |> -> Exec['apt_update']
  }

  # Require apt update to run before package resource.
  Exec['apt_update'] -> Package <| title != 'dirmngr' and title != 'debian-keyring' and title != 'debian-archive-keyring' |>
```
I also do things like this in modules that I've written that internally manage a repo (like Docker). Here is one called `cvmfs`
```
 Apt::Source <| tag == 'cvmfs' |> -> Exec['apt_update'] -> Package <| tag == 'cvmfs' |>
```
This relies on the fact that the module name is applied as a tag to all the resources within.
