### ISSUE TITLE
docker-run.erb - undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by timdeluxe** [puppetlabs/puppetlabs-docker#461] opened 2019-03-19 14:39 UTC
## What you expected to happen?
clean puppet run

## What happened?
```
Warning: Unknown variable: 'docker::service_name'. (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 153, column: 19)
Warning: Unknown variable: 'docker::docker_group'. (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 154, column: 19)
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template docker/etc/systemd/system/docker-run.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/docker/templates/etc/systemd/system/docker-run.erb
  Line: 3
  Detail: undefined method `+' for nil:NilClass
 (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 443, column: 20) (file: /tmp/helloworld.pp, line: 1) on node foobar
```

## How to reproduce it?
Install module:
`puppet module install puppetlabs-docker`
Create file helloworld.pp:
```
 docker::run {
    "helloworld":
      hostname => "helloworld",
      image => "hello-world:latest",
  }
```
Run
`puppet apply -v helloworld.pp`

## Anything else we need to know?
Version 3.3.0 of the module works 

## Versions:

```
$ puppet --version
5.5.3
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
$ facter os
{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.6 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
$ puppet module list
/etc/puppetlabs/code/environments/production/modules
├── puppetlabs-apt (v6.3.0)
├── puppetlabs-docker (v3.5.0)
├── puppetlabs-powershell (v2.2.0)
├── puppetlabs-reboot (v2.1.2)
├── puppetlabs-stdlib (v5.2.0)
└── puppetlabs-translate (v1.2.0)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
```

## Logs:
See "What happened"

**Comment by martialblog** [comment] 2019-03-20 09:46
Hi, I managed to recreate that issue. 

```
docker run -ti --entrypoint bash puppet/puppet-agent-ubuntu

# With 3.4.0
/opt/puppetlabs/bin/puppet module install --force --version 3.4.0 puppetlabs-docker
/opt/puppetlabs/bin/puppet apply /helloworld.pp 
Warning: Unknown variable: 'docker::service_name'. (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 147, column: 19)
Warning: Unknown variable: 'docker::docker_group'. (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 148, column: 19)
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template docker/etc/systemd/system/docker-run.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/docker/templates/etc/systemd/system/docker-run.erb
  Line: 3
  Detail: undefined method `+' for nil:NilClass
 (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 437, column: 20) (file: /helloworld.pp, line: 1) on node fb81c368c376.iis.fhg.de

# With 3.3.0 (systemd not installed, disregard the error)
/opt/puppetlabs/bin/puppet module install --force --version 3.3.0 puppetlabs-docker
/opt/puppetlabs/bin/puppet apply /helloworld.pp 
Notice: Compiled catalog for fb81c368c376.iis.fhg.de in environment production in 0.22 seconds
Notice: /Stage[main]/Main/Docker::Run[helloworld]/File[/usr/local/bin/docker-run-helloworld-start.sh]/group: group changed 'root' to 'docker'
Notice: /Stage[main]/Main/Docker::Run[helloworld]/File[/usr/local/bin/docker-run-helloworld-stop.sh]/group: group changed 'root' to 'docker'
Notice: /Stage[main]/Main/Docker::Run[helloworld]/File[/etc/systemd/system/docker-helloworld.service]/group: group changed 'root' to 'docker'
Notice: /Stage[main]/Main/Docker::Run[helloworld]/Exec[docker-helloworld-systemd-reload]/returns: Failed to connect to bus: No such file or directory
Error: /Stage[main]/Main/Docker::Run[helloworld]/Exec[docker-helloworld-systemd-reload]: Failed to call refresh: 'systemctl daemon-reload' returned 1 instead of one of [0]
Error: /Stage[main]/Main/Docker::Run[helloworld]/Exec[docker-helloworld-systemd-reload]: 'systemctl daemon-reload' returned 1 instead of one of [0]
Error: /Stage[main]/Main/Docker::Run[helloworld]/Service[docker-helloworld]: Provider systemd is not functional on this host
Notice: Applied catalog in 0.03 seconds
```

I'm trying to pinpoint what's causing it.

**Comment by martialblog** [comment] 2019-03-20 10:00
I think this change is to blame: https://github.com/puppetlabs/puppetlabs-docker/pull/431

https://github.com/puppetlabs/puppetlabs-docker/pull/431/files#diff-2ce9d112c9edac69817e7f77c5d2522c

According to the changes, the run.pp now requires the service_name and docker_group as parameters:
```
  $service_name = $docker::service_name
  $docker_group = $docker::docker_group
```

However, the class has no such parameters. Do I understand that correct: The main class *always* has to be included? If so that needs to be reflected in the README

**Comment by davejrt** [comment] 2019-03-20 10:50
That is correct that the main class always needs to be included in the manifest. We can update the README but I'm interested to know why you wouldn't be including it in the manifest. Are you installing docker and managing other aspects of the installation elsewhere?

**Comment by martialblog** [comment] 2019-03-20 11:09
@davejrt I see. Makes sense, since you "probably" want Docker installed on the machine that run a container :whale: 

We encountered this issue in our spec tests. Since we're managing the main docker class separatly from the actual Images/Containers. So both have their own Profile, but obviously both are included.

When reading the README now it kinda makes sence... First you Setup, then you Usage. But i can still see people running into the issue here (including myself it seems), so a hint/common gotchas would be nice.

Cheers, Markus

**Comment by davejrt** [comment] 2019-03-20 11:21
We'll ensure this is explicit in the next release of the module

**Comment by martialblog** [comment] 2019-03-20 11:49
@davejrt Awesome. Thanks!

**Comment by mojibake-umd** [comment] 2019-04-03 12:23
Experiencing same issue, not sure how to work around....
We have main docker class declared in a puppet module to setup our application.
We also have a separate puppet module to setup AWS ECS Agent, it is this module that has issues as the puppet module only declares the run class. (Performs other things related to install ECS agent too)
Like the OP, experienced the same error in our module for ECS Agent, however I was able to easily punt around with problem with a pre_condition in our rspec test declaring the docker class and passing those needed params.
However the problem lies when trying to actually apply on the EC2 instance.
Being that  RHEL7 based EC2 instance the docker group should default to 'dockerroot' as 'use_upstream_package_source' is set to false per README.
Despite attempting to explicitly set docker::group_name and docker::service_name in hiera puppet still fails with 
```
Error: Could not find group docker
Error: /Stage[main]/Ecs_agent::Service/Docker::Run[ecs-agent]/File[/etc/systemd/system/docker-ecs-agent.service]/group: change from root to docker failed: Could not find group docker
```
Which tells me  that docker::run is not accessing those parameters at all.
Also attempts of cross-class inheritance, "inherits docker" in my ECS Agent wrapper module which declares docker::run does not work either.

Can't group_name and service_name be added as parameters to run.pp? 
Like
$ group_name = $::docker::group_name
$ service_name = $::docker::service_name
I can make a pull request if these seems like a reasonable solution.
Maybe I am just too inexperienced to know how to work around the problem.

**Comment by martialblog** [comment] 2019-04-03 12:29
@mojibake-umd Did you include the puppetlabs-docker module? Or just the docker::run?

Cause you gotta have `include docker` somewhere. This is also where you can setup the group 

https://github.com/puppetlabs/puppetlabs-docker#docker_group

**Comment by mojibake-umd** [comment] 2019-04-03 12:45
@martialblog Thank you for the suggestion.
I included docker in the manifest which declared docker::run just now while setting in heira
```
docker::service_name: 'docker'
docker::group_name: 'dockerroot'
```
As mentioned in previous comment, main docker itself is declared and setup for RHEL7 in another puppet module for our application. (Works thanks to #441 )

Unfortunately 
```include '::docker'```
plus
Hiera
```
docker::service_name: 'docker'
docker::group_name: 'dockerroot'
```
does not work.

**Comment by martialblog** [comment] 2019-04-04 07:53
@mojibake-umd Hm, I don't think you experiencing the same issue then. What's the error you're getting?

**Comment by mojibake-umd** [comment] 2019-04-10 17:23
@martialblog Insert Homer "Doh!" image here....
I just realized I was trying to set docker::group_name in hiera, and not docker::docker_group.
All is well after ```include docker``` and
```
docker::service_name: 'docker'
docker::docker_group: 'dockerroot'
docker::socket_group: 'dockerroot'
```

**Comment by blackknight36** [comment] 2019-05-08 14:33
Even added an 'include docker' statement does not fix this.  Puppet now fails with an error as shown below.

```
Info: Using configured environment 'docker'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'docker/etc/systemd/system/docker.service.d/service-overrides-rhel.conf.erb' at /etc/puppetlabs/code/environments/mdct_docker/forge_modules/docker/manifests/service.pp:172:22 on node docker.example.com                                                                                                              
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
Reinstalling the module on our master does not help, the template file does not exist.

```
[root@puppetmaster docker]# find templates/etc/systemd/system/docker.service.d/
templates/etc/systemd/system/docker.service.d/
```

Puppetfile is configured to pull the 3.5.0 release.  Is there a way to resolve this other than pulling from the master branch?

**Comment by martialblog** [comment] 2019-05-08 15:05
@blackknight36 I don't think this is the same issue, this had nothing to do with templates. [Stackoverflow](https://stackoverflow.com/questions/tagged/puppet) might be a better place to ask for help in this case.

However, I would try to remove and redeploy the module using r10k (or whatever you use for deployment), since the module doesn't seem to be deployed properly.

**Comment by blackknight36** [comment] 2019-05-08 17:33
@martialblog The issues are related, I was getting the undefined method error until I added the "include docker" statement to my manifest.  After that the template error shows up due to a missing template file in the module.  I was able to resolve this by setting my puppetfile to pull from *master* but using 3.5.0 results in template errors.

**Comment by davejrt** [comment] 2019-05-08 19:16
@blackknight36 can you please post a full manifest? This module is tested on RHEL with include docker as part of nightly acceptance testing. and I have just tested on another rhel instance without issue.

**Comment by hboetes** [comment] 2019-05-21 09:07
No time for a pull request, but I just ran into the same error:
```
diff --git a/templates/etc/systemd/system/docker-run.erb b/templates/etc/systemd/system/docker-run.erb
index 7eccfd2..6c2397a 100644
--- a/templates/etc/systemd/system/docker-run.erb
+++ b/templates/etc/systemd/system/docker-run.erb
@@ -1,11 +1,11 @@
 <%-
        depend_services = @depend_services_array.map{|s| s =~ /\.[a-z]+$/ ? s : "#{s}.service"}
-       @after = [@service_name+".service"] +
+       @after = ["#{@service_name}.service"] +
                @sanitised_after_array.map{ |s| "#{@service_prefix}#{s}.service"} +
                @sanitised_depends_array.map{ |s| "#{@service_prefix}#{s}.service"} +
                depend_services
        @wants = @sanitised_after_array.map{ |a| "#{@service_prefix}#{a}.service"}
-       @requires = [@service_name+".service"] +
+       @requires = ["#{@service_name}.service"] +
                @sanitised_depends_array.map{ |d| "#{@service_prefix}#{d}.service"} +
                depend_services
 -%>
```

**Comment by blackknight36** [comment] 2019-05-21 15:00
@davejrt Posting a full manifest would be difficult due to the number of included classes we use but I am able to reproduce this error by adding the following line to our puppetfile.

```
mod 'puppetlabs-docker',            '3.5.0'
```

This results in a copy of the docker module which is missing the service-overrides-rhel.conf.erb file.  Here's a listing of all templates that exist on the master.

```
[root@mdct-puppetmaster system]# pwd
/etc/puppetlabs/code/environments/mdct_docker/forge_modules/docker/templates/etc/systemd/system
[root@mdct-puppetmaster system]# find .
.
./docker-run.erb
./docker.service.d
./docker.socket.d
./docker.socket.d/socket-overrides.conf.erb
```

As you can see there is no template named service-overrides-rhel.conf.erb.

To fix this the puppetfile needs to be adjusted to pull from the master branch as follows.

```
mod 'puppetlabs-docker',
    :git => 'https://github.com/puppetlabs/puppetlabs-docker.git'
```

**Comment by carabasdaniel** [comment] 2021-01-18 10:36
Closing this issue as it's for an older version of the module. 
If the problem persists please feel free to re-open the issue.

**Closed by carabasdaniel** 2021-01-18 10:36 UTC
Labels: bugfix
