### ISSUE TITLE
Version is not honored for dependencies

### ISSUE THREAD

**Issue by pier4r** [puppetlabs/puppetlabs-docker#690] opened 2020-12-10 15:50 UTC
## Describe the Bug
If I set the attribute version to `version    => '19.03.14-3.el7',` I expect that all the dependencies respect the version or at least do not get new ones. Instead the result ist the following (CentOs 7.9)
```
docker-ce.x86_64                     3:19.03.14-3.el7                  @docker
docker-ce-cli.x86_64                 1:20.10.0-3.el7                   @docker
```

## Expected Behavior
I would expect the dependencies not being newer than the major package, thus
```
docker-ce.x86_64                     3:19.03.14-3.el7                  @docker
docker-ce-cli.x86_64                 3:19.03.14-3.el7                    @docker
```

## Steps to Reproduce
1. Set the version to ` '19.03.14-3.el7'` on an uptodate CentOS system
2. let puppet run
3. check the version with 'yum list installed | grep -i docker'

## Environment
 - Version 3.11.0
 - Platform CentOS 7.9.x

**Comment by somasusr** [comment] 2020-12-16 01:14
Facing the same issue. Since we are currently using 3.8.0 version of this module, tried to downgrade docker version back to 19.03.14, but it only updates docker-ce, but not docker-ce-cli.

Also, tried to move to latest version on this module 3.13.0, but getting the below error while creating a user-defined bridge network.

Error: Could not find a suitable provider for docker_network

**Comment by stefanlasiewski** [comment] 2021-02-11 23:12
I think this is a duplicate of #597

**Closed** 2021-06-28 08:54 UTC
Labels: bug
